version: '3'

services:
  api:
    build: ./taskManager
    ports:
      - "8000:8000"
    volumes:
      - ./taskManager:/taskManager

  web:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/front-end
