export const GET_TASKS_LIST_START = "GET_TASKS_LIST_START";
export const GET_TASKS_LIST_FAIL = "GET_TASKS_LIST_FAIL";
export const GET_TASKS_LIST_SUCCESS = "GET_TASKS_LIST_SUCCESS";

export const CREATE_TASK_START = "CREATE_TASK_START";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";